# Generated by Django 4.1.7 on 2023-02-24 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreD', models.CharField(max_length=255, verbose_name='Nombre del paciente')),
                ('NDiente', models.CharField(max_length=255, verbose_name='Nombre del paciente')),
                ('Descripcion', models.CharField(max_length=255, verbose_name='Descripcion')),
                ('fechaD', models.DateTimeField(auto_now_add=True)),
                ('fecha_actD', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('nombreD',),
            },
        ),
        migrations.CreateModel(
            name='ExpedienteO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreO', models.CharField(max_length=255, verbose_name='Nombre del paciente')),
                ('gojoD', models.CharField(max_length=255, verbose_name='Graduacion ojo derecho')),
                ('gojoI', models.CharField(max_length=255, verbose_name='Graduacion ojo izquierdo')),
                ('padecimientos', models.CharField(max_length=255, verbose_name='Padecimientos')),
                ('cambioMicas', models.CharField(max_length=255, verbose_name='Cambio de micas')),
                ('fechaO', models.DateTimeField(auto_now_add=True)),
                ('fecha_actO', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('nombreO',),
            },
        ),
        migrations.CreateModel(
            name='ExpedienteG',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreG', models.CharField(max_length=255, verbose_name='Nombre del paciente')),
                ('peso', models.CharField(max_length=20, verbose_name='Talla')),
                ('operaciones', models.CharField(max_length=255, verbose_name='Operaciones')),
                ('lesiones', models.CharField(max_length=255, verbose_name='Lesiones')),
                ('alergias', models.CharField(max_length=255, verbose_name='Alergias')),
                ('enfermedades', models.CharField(max_length=255, verbose_name='Enfermedades')),
                ('tipoSangre', models.CharField(max_length=255, verbose_name='Tipo de Sangre')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('fecha_actG', models.DateTimeField(auto_now=True)),
                ('idPg', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('nombreG',),
            },
        ),
    ]
